---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
  labels:
    service: suricata
  name: suricata
  namespace: suricata
spec:
  selector:
    matchLabels:
      service: suricata
  template:
    metadata:
      annotations:
      labels:
        service: suricata
    spec:
      automountServiceAccountToken: false

      hostNetwork: true

      containers:
        - name: suricata
          image: jasonish/suricata:6.0.4-amd64
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: suricata
                  resource: limits.cpu
            - name: SURICATA_OPTIONS
              value: "-i eth0 -vvv --set sensor-name=suricata --set af-packet.1.threads=$(CPU_LIMIT) --set outputs.7.pcap-log.filename=log.$(NODE_NAME).%n.%t.pcap --set outputs.1.eve-log.filename=$(NODE_NAME)-eve.json"
          command: ["/etc/suricata/new_entrypoint.sh"]

          resources:
            requests:
              memory: 1Gi
              cpu: 200m
            limits:
              cpu: 2
              memory: 4Gi

          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_NICE

          volumeMounts:
            - mountPath: /var/log/suricata
              name: suricata-log
            - mountPath: /var/run/suricata
              name: suricata-run
            - mountPath: /etc/suricata/rules
              name: suricata-rules
            - mountPath: /etc/suricata/selks6-addin.yaml
              name: suricata-etcselks6-addin
              subPath: selks6-addin.yaml
            - mountPath: /etc/suricata/new_entrypoint.sh
              name: suricata-new-entrypoint
              subPath: new_entrypoint.sh
            - mountPath: /docker-entrypoint.sh
              name: suricata-docker-entrypoint
              subPath: docker-entrypoint.sh
            - mountPath: /etc/logrotate.d
              name: suricata-logrotate

      securityContext:
        fsGroup: 995
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault

      volumes:
        - name: suricata-log
          persistentVolumeClaim:
            claimName: suricata-log
        - name: suricata-run
          persistentVolumeClaim:
            claimName: suricata-run
        - name: suricata-rules
          persistentVolumeClaim:
            claimName: suricata-rules

        - name: suricata-etcselks6-addin
          configMap:
            name: suricata-etc
            items:
              - key: selks6-addin.yaml
                path: selks6-addin.yaml
                mode: 0444
        - name: suricata-new-entrypoint
          configMap:
            name: suricata-etc
            items:
              - key: new_entrypoint.sh
                path: new_entrypoint.sh
                mode: 0555
        - name: suricata-docker-entrypoint
          configMap:
            name: suricata-etc
            items:
              - key: docker-entrypoint.sh
                path: docker-entrypoint.sh
                mode: 0555
        - name: suricata-logrotate
          configMap:
            name: suricata-etc
            items:
              - key: logrotate
                path: suricata
                mode: 0444
