version: '3.3'

networks:
  selks:

volumes:
  kibana-dashboards:

services:
  
  elasticsearch:
    container_name: SELKS-elasticsearch
    image: elasticsearch:7.12.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      selks:
        aliases:
          - elasticsearch
      
  kibana:
    container_name: SELKS-kibana
    image: kibana:7.12.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:5601 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      selks:
        aliases:
          - kibana
    ports:
      - 5601:5601
    
  logstash:
    container_name: SELKS-logstash
    image: logstash:7.12.0
    restart: unless-stopped
    depends_on:
      scirius:
        condition: service_healthy #because we need to wait for scirius to populate ILM policy
    volumes:
      - ./containers-data/suricata/log:/var/log/suricata:ro
      - ./containers-data/logstash/conf.d/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./containers-data/logstash/templates/elasticsearch7-template.json:/usr/share/logstash/config/elasticsearch7-template.json
    networks:
      selks:
        aliases:
          - logstash
          
  suricata:
    container_name: SELKS-suricata
    image: jasonish/suricata:6.0.2
    restart: unless-stopped
    environment:
      - SURICATA_OPTIONS=${INTERFACES} -vvv --set sensor-name=suricata
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    network_mode: host
    volumes:
       - ${SURICATA_LOGS_PATH:-./containers-data/suricata/log}:/var/log/suricata
       - ./containers-data/suricata/rules/:/etc/suricata/rules
       - ./containers-data/suricata/run/:/var/run/suricata/
    
  scirius:
    container_name: SELKS-scirius
    build:
      context: https://github.com/yodapotatofly/docker-scirius.git#${BRANCH:-master}
      args:
        VERSION: ${SCIRIUS_VERSION:-master}
    image: scirius:${SCIRIUS_VERSION:-master}-${DATE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 180s
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=p8o5%vq))8h2li08c%k3id(wwo*u(^dbdmx2tv#t(tb2pr9@n-
      - DEBUG=${SCIRIUS_DEBUG:-False}
      - SCIRIUS_IN_SELKS=True
      - USE_ELASTICSEARCH=True
      - ELASTICSEARCH_ADDRESS=elasticsearch:9200 #Default
      - USE_KIBANA=True
      - KIBANA_URL=http://kibana:5601 #Default
      - KIBANA_PROXY=True
      - ALLOWED_HOSTS=*
      - KIBANA7_DASHBOARDS_PATH=/opt/selks/kibana7-dashboards
      - SURICATA_UNIX_SOCKET=/var/run/suricata/suricata-command.socket
      - USE_EVEBOX=True
      - EVEBOX_ADDRESS=evebox:5636 #Default
      - USE_SURICATA_STATS=True
      
      
    volumes:
      - ./containers-data/scirius/static/:/static/
      - ./containers-data/suricata/rules/:/rules
      - ./containers-data/suricata/run:/var/run/suricata
    networks:
      selks:
        aliases:
          - scirius
          
  evebox:
    container_name: SELKS-evebox
    image: jasonish/evebox:master
    command: ["-e", "http://elasticsearch:9200"]
    restart: unless-stopped
    ports:
      - 5636:5636
    networks:
      selks:
        aliases:
          - evebox
     
  nginx:
    container_name: SELKS-nginx
    image: nginx
    command: ['${NGINX_EXEC:-nginx}', '-g', 'daemon off;']
    restart: unless-stopped
    volumes:
      - ./containers-data/scirius/static/:/static/:ro
      - ./containers-data/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./containers-data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./containers-data/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - 80:80
      - 443:443
    networks:
      selks:
        aliases:
          - nginx
