---

apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  type: ClusterIP
  ports:
    - port: 2020
      protocol: TCP
      name: fluent-bit
      targetPort: 2020
  selector:
    app: fluent-bit
