---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: arkime-log
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: arkime-log
    namespace: suricata
  local:
    path: /data/suricata/arkime/logs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - localhost.localdomain
