---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: elasticsearch-data
  name: elasticsearch-data
  namespace: elasticsearch
spec:
  storageClassName: "local-storage"
  volumeName: elasticsearch-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
