---

apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: suricata
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: filestream
      paths:
        - /var/log/suricata/*.json
      json.keys_under_root: true

    processors:
    - add_fields:
        target: ''
        fields:
          type: "SELKS"

    output.logstash:
      enabled: true
      host: '${NODE_NAME}'
      hosts: ["logstash.logging.svc.cluster.local:5044"]
      worker: 1
