---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: scirius-logs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: scirius-logs
    namespace: suricata
  local:
    path: /data/scirius/logs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - HOSTNAME

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: scirius-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: scirius-data
    namespace: suricata
  local:
    path: /data/scirius/data/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - HOSTNAME

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: scirius-static
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: scirius-static
    namespace: suricata
  local:
    path: /data/scirius/static/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - HOSTNAME
