---

apiVersion: v1
kind: Service
metadata:
  name: scirius
  namespace: suricata
  labels:
    app: scirius
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 8000
  selector:
    app: scirius
